[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "schema-fixture-cli"
dynamic = ["version"]
version = "0.1.0"
description = "Generates realistic test data from schemas"
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT"}
authors = [{name = "Arya Sianati", email = "arya@cycoders.com"}]
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest >=7.4",
    "black",
    "ruff",
    "rich",
]

[project.scripts]
schema-fixture = "schema_fixture_cli.cli:main"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-ra --strict-markers --strict-config"

[tool.black]
target-version = ['py311']

[tool.ruff]
target-version = "py311"
line-length = 100
select = ["E", "F", "B", "A", "C4", "PT", "SIM"]
ignore = ["SIM118"]
