[tool.poetry]
name = "sbom-generator-cli"
version = "0.1.0"
description = "Generates SBOMs in SPDX/CycloneDX from package lockfiles"
authors = ["Arya Sianati <arya@cycoders.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/cycoders/code/tree/main/sbom-generator-cli"
keywords = ["sbom", "cyclonedx", "spdx", "supply-chain", "security"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Topic :: Software Development :: Quality Assurance",
]

[tool.poetry.dependencies]
python = ">=3.11"
typer = {extras = ["all"], version = "^0.12.0"}
rich = "^13.7.1"
pydantic = "^2.8.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
pytest-mock = "^3.14.0"
ruff = "^0.6.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 100

[tool.pytest.ini_options]
minversion = "8.3"
addopts = "-ra --strict-markers"
testpaths = ["tests"]
filterwarnings = [
    "ignore::pytest.PytestCollectionWarning",
]
