[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "i18n-extractor"
dynamic = ["version"]
description = "Extracts translatable strings from Python codebases handling literals, f-strings and format calls in gettext functions for i18n workflows"
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT"}
authors = [
  {name = "Arya Sianati", email = "arya@cycoders.com"},
]
dependencies = [
  "typer >= 0.9.0",
  "rich >= 13.7.0",
]

[project.optional-dependencies]
dev = [
  "pytest >= 7.4.0",
]

[project.scripts]
i18n-extractor = "i18n_extractor.main:app"

[project.urls]
Homepage = "https://github.com/cycoders/code/tree/main/i18n-extractor"

[tool.hatch.version]
path = "src/i18n_extractor/__init__.py"

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q"
testpaths = "tests"
