[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gha-visualizer"
version = "0.1.0"
description = "CLI tool to generate interactive Mermaid diagrams and analytics reports from GitHub Actions workflows."
readme = "README.md"
license = "MIT"
requires-python = ">=3.11"
authors = [{name = "Arya Sianati"}]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "typer>=0.12.0",
    "rich>=13.7.0",
    "PyYAML>=6.0.1",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
]

[project.scripts]
gha-viz = "gha_visualizer.cli:app"

[tool.setuptools.packages.find]
where = ["src"]
include = ["gha_visualizer*"]

[tool.setuptools.package-dir]
"" = ["src"]