apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-app
  namespace: prod
spec:
  replicas: 1
  selector: {}
  template:
    metadata: {}
    spec:
      hostNetwork: true
      containers:
      - name: nginx
        image: nginx:latest
        resources: {}
        securityContext:
          privileged: true
          runAsUser: 0
        ports:
        - containerPort: 80
          hostPort: 8080
        # No probes
      volumes:
      - emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: bad-svc
  namespace: prod
spec:
  type: LoadBalancer
  ports:
  - port: 80
