[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "license-checker-cli"
dynamic = ["version"]
description = "Unified CLI to audit OSS licenses in Python and Node.js deps"
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.11"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
]

[project.scripts]
license-checker = "license_checker_cli.cli:app"

[tool.hatch.version]
path = "src/license_checker_cli/__init__.py"

[project.optional-dependencies]
dev = ["pytest>=7.4.0", "pytest-mock>=3.11.0"]
