[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "formatter-preview"
dynamic = ["version"]
description = "Preview formatter diffs from Ruff and Prettier"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "typer >= 0.12.5",
  "rich >= 13.7.1",
]
license = {file = "LICENSE"}
authors = [
  {name = "Arya Sianati", email = "arya@cycoders.com"},
]

[project.optional-dependencies]
dev = [
  "pytest >= 7.0",
  "ruff",
  "pre-commit",
]

[project.scripts]
formatter-preview = "formatter_preview.__main__:main"

[tool.pytest.ini_options]
addopts = "-ra -q --strict-markers"
testpaths = ["tests"]
filterwarnings = [
  "ignore::DeprecationWarning",
]

[tool.ruff]
line-length = 88