[build-system]
requires = ["hatchling>=1.0"]
build-backend = "hatchling.build"

[project]
name = "http-signer-cli"
dynamic = ["version"]
description = "CLI for signing HTTP requests with AWS SigV4, OAuth 1.0a and more"
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.11"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Topic :: Software Development :: Testing",
    "Topic :: Utilities",
]
authors = [
  {name = "Arya Sianati", email = "arya@cycoders.com"},
]
dependencies = [
    "typer>=0.12.0",
    "rich>=13.7.0",
    "pyperclip>=1.9.0",
]
[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-typer",
    "freezegun",
    "ruff",
]
[project.scripts]
http-signer-cli = "http_signer_cli.cli:app"

[project.urls]
Homepage = "https://github.com/cycoders/code/tree/main/http-signer-cli"
Repository = "https://github.com/cycoders/code"

[tool.hatch.version]
path = "src/http_signer_cli/__init__.py"

[tool.hatch.build.targets.sdist]
include = [
    "src/http_signer_cli",
    "README.md",
    "LICENSE",
]

[tool.pytest.ini_options]
minversion = "7.4"
testpaths = ["tests"]
addopts = "-ra --strict-markers"
filterwarnings = [
    "ignore::DeprecationWarning",
]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "B", "A", "C4", "PT", "UP", "W", "ARG", "PTH"]
ignore = ["B008"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
