[tool.pytest.ini_options]
addopts = "-q --strict-markers --strict-config"
minversion = "7.0"
testpaths = ["tests"]

[tool.black]
line-length = 100
target-version = ['py311']

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "B", "Q", "I", "N", "ARG", "P", "UP", "W", "YTT"]
ignore = ["B008"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F403", "F405"]

[tool.ruff.format]
quote-style = "double"