[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "8.0"
testpaths = ["tests"]
addopts = "-ra --cov=src --cov-report=term-missing"
filterwarnings = [
    "ignore::DeprecationWarning:cssutils",
]

[tool.black]
target-version = ['py311']
include = '\.pyi?$'