[build-system]
requires = ["setuptools>=65", "wheel", "hatchling"]
build-backend = "hatchling.build"

[project]
name = "sql-erd-cli"
dynamic = ["version"]
description = "Generate ERDs from SQL DDL files"
readme = "README.md"
requires-python = ">=3.11"
license = {file = "LICENSE"}
authors = [{name = "Arya Sianati", email = "arya@example.com"}]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = [
  "typer",
  "rich",
  "sqlglot",
  "graphviz",
]

[project.scripts]
sql-erd-cli = "sql_erd_cli.__main__:main"

[project.optional-dependencies]
dev = [
  "pytest>=7.0",
  "pytest-cov",
  "black",
  "ruff",
]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra --cov=sql_erd_cli --cov-report=term-missing"
testpaths = ["tests"]

[tool.black]
target-version = ['py311']

[tool.ruff]
line-length = 100
target-version = "py311"