[tool.pytest.ini_options]
addopts = "-q --strict-markers -r w"
testpaths = ["tests"]
filterwarnings = ["ignore::DeprecationWarning"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
